networks:
  trains_network:
    driver: bridge

services:
  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - trains_network

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
      - "19092:19092"
    networks:
      - trains_network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Data sensor simulator as Kafka producer
  data_sensor_simulator_kafka_producer:
    build:
      context: ./kafka_producer
      dockerfile: Dockerfile
    container_name: kafka_producer
    hostname: producer
    environment:
      KAFKA_BROKER: 'kafka:9092'
      TOPIC_NAME: "train-sensor-data"
    depends_on:
      - kafka
    networks:
      - trains_network
    entrypoint: ["/wait-for-it.sh", "kafka:9092", "--", "sh", "-c", "python data_simulator.py"]

  # Flask application as Kafka consumer
  flask_app_kafka_consumer:
    build:
      context: ./kafka_consumer
      dockerfile: Dockerfile
    container_name: kafka_consumer
    hostname: consumer
    environment:
      KAFKA_BROKER: 'kafka:9092'
      TOPIC_NAME: 'train-sensor-data'
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    networks:
      - trains_network
    entrypoint: ["/wait-for-it.sh", "kafka:9092", "--", "sh", "-c", "flask run"]
