kafka_topic_update_interval_secs: 10
logging_level: debug

wandb:
  run_name: debug
  
default_vehicle_config:
  # The rate of information (i.e., time) is multiplied x 100 for the sake of speeding up the simulation
  mu_anomalies: 0.157
  mu_normal: 0.117


default_consumer_config:
  weights_push_freq_seconds: 15
  weights_pull_freq_seconds: 15
  epoch_size: 2
  save_model_freq_epochs: 2

federated_learning:
  aggregation_strategy: fedyogi
  aggregation_interval_secs: 7
  weights_buffer_size: 2