wandb:
  run_name: fed_AVG

default_vehicle_config:
  # The rate of information (i.e., time) is multiplied x 100 for the sake of speeding up the simulation
  mu_anomalies: 1.57
  mu_normal: 1.17

federated_learning:
  aggregation_strategy: fedavg    # fedavg, fedyogi
  aggregation_interval_secs: 20     


default_consumer_config:
  weights_push_freq_seconds: 120
  weights_pull_freq_seconds: 120
  learning_rate: 0.002