
override: ""

logging_level: info
container_manager_port: 7777

default_vehicle_config:
  kafka_broker: kafka:9092
  mu_anomalies: 157
  mu_normal: 117
  alpha: 0.2
  beta: 1.9


vehicles:
  - vehicle1


dashboard:
  port: 5000
  host: 0.0.0.0
  kafka_broker_url: localhost:19092
  kafka_consumer_group_id: kafka-consumer-group-1
  kafka_auto_offset_reset: earliest
  message_cache_len: 100