

logging_level: info
container_manager_port: 7777
vehicle_names:
  - tom

dashboard:
  port: 5000
  host: 0.0.0.0
  kafka_broker_url: localhost:19092
  kafka_consumer_group_id: kafka-consumer-group-1
  kafka_auto_offset_reset: earliest