
override: ""

logging_level: info
container_manager_port: 7777
kafka_topic_update_interval_secs: 30

wandb:
  online: true
  project_name: OPEN_FAIR
  run_name: My_awesomre_FAIR_run
  kafka_broker_url: kafka:9092
  kafka_consumer_group_id: WANDBER
  kafka_auto_offset_reset: earliest

federated_learning:
  aggregation_strategy: fedavg    # fedavg, fedyogi
  initialization_strategy: xavier   # xavier, he, normal
  aggregation_interval_secs: 30     
  weights_buffer_size: 5

default_vehicle_config:
  kafka_broker: kafka:9092
  mu_anomalies: 157
  mu_normal: 117
  alpha: 0.2
  beta: 1.9
  anomaly_classes: all
  diagnostics_classes: all


vehicles:
  - angela:
      anomaly_classes: 
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      diagnostics_classes:
        - 0
        - 1 
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
  - bob:
      anomaly_classes:
        - 3 
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
      diagnostics_classes:
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
  - claude:
      anomaly_classes:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
      diagnostics_classes:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14

default_consumer_config:
  buffer_size: 5000
  batch_size: 32
  kafka_broker: kafka:9092
  kafka_auto_offset_reset: earliest
  anomaly_classes: all
  diagnostics_classes: all
  weights_push_freq_seconds: 180
  weights_pull_freq_seconds: 180
  learning_rate: 0.001
  
dashboard:
  port: 5000
  host: 0.0.0.0
  kafka_broker_url: localhost:19092
  kafka_consumer_group_id: kafka-consumer-group-1
  kafka_auto_offset_reset: earliest
  message_cache_len: 20